import {createHmac,timingSafeEqual,createHash} from 'node:crypto';
import {AppError,validateState} from './domain.mjs';
import {extractDraft} from './gemini.mjs';
export function validSignature(raw,signature,secret){if(!secret||typeof signature!=='string')return false;const expected=createHmac('sha256',secret).update(raw).digest('base64');const a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}
export function draftEntry(d,text,eventId){if(d.warnings?.length||!d.title||!['record','task'].includes(d.kind)||(d.kind==='record'&&(!d.orgId||!d.date)))return null;const common={id:'line-'+createHash('sha256').update(eventId).digest('hex').slice(0,48),title:d.title,note:d.note||'',sourceText:text};return d.kind==='task'?{...common,org:d.orgId||null,dueDate:d.date||null,done:false}:{...common,org:d.orgId,date:d.date,endDate:d.endDate||null,relatedOrg:null,type:d.type,amount:d.amount??null};}
export function createLineService({store,config,ai=extractDraft,fetchImpl=fetch}){
 const allowed=new Set((config.lineAllowedUsers||'').split(',').map(x=>x.trim()).filter(Boolean));let working=false,timer;
 const enabled=()=>Boolean(config.lineSecret&&config.lineToken&&allowed.size);
 async function init(){await store.pool.query(`CREATE TABLE IF NOT EXISTS cb_line_jobs(id text PRIMARY KEY,event jsonb NOT NULL,status text NOT NULL DEFAULT 'pending',lease_until timestamptz,reply_text text,created_at timestamptz NOT NULL DEFAULT now());`);}
 async function webhook(req){if(!config.lineSecret)throw new AppError(503,'尚未設定 LINE Channel Secret');let size=0,parts=[];for await(const p of req){size+=p.length;if(size>1024*1024)throw new AppError(413,'LINE 訊息過大');parts.push(p);}const raw=Buffer.concat(parts);if(!validSignature(raw,req.headers['x-line-signature'],config.lineSecret))throw new AppError(401,'LINE 簽章不正確');let payload;try{payload=JSON.parse(raw.toString('utf8'));}catch{throw new AppError(400,'LINE 訊息格式不正確');}if(!Array.isArray(payload.events)||payload.events.length>100)throw new AppError(400,'LINE 事件格式不正確');if(payload.events.length&&!enabled())throw new AppError(503,'請先設定 LINE Token 與允許的使用者 ID');
 const c=await store.pool.connect();try{await c.query('BEGIN');for(const e of payload.events){if(e.source?.type!=='user'||!allowed.has(e.source.userId)||e.type!=='message')continue;if(typeof e.webhookEventId!=='string'||e.webhookEventId.length>100||typeof e.replyToken!=='string')continue;await c.query('INSERT INTO cb_line_jobs(id,event) VALUES($1,$2) ON CONFLICT DO NOTHING',[e.webhookEventId,e]);}await c.query('COMMIT');}catch(err){await c.query('ROLLBACK');throw err;}finally{c.release();}return {ok:true};}
 async function reply(e,text){const r=await fetchImpl('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.lineToken},body:JSON.stringify({replyToken:e.replyToken,messages:[{type:'text',text:text.slice(0,4900)}]}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('LINE_REPLY_'+r.status);}
 async function process(job){const e=job.event;let answer=job.reply_text;if(!answer){if(e.message?.type!=='text'){answer='目前支援文字紀錄，照片與語音尚未開放。';}else{const text=e.message.text;if(typeof text!=='string'||!text.trim()||text.length>8000)answer='請傳送 8000 字以內的文字。';else if(['說明','help','開始'].includes(text.trim().toLowerCase()))answer='直接傳送要記錄的事情或待辦，例如：2026/10/18～10/23 金澤出差，搭華航商務艙。內容明確會直接儲存；有疑問會請你補充。查看或修改：'+config.origin;else{try{const state=await store.read(),id='line-'+createHash('sha256').update(job.id).digest('hex').slice(0,48);let kind=state.tasks.some(x=>x.id===id)?'task':'record',entry=state.tasks.find(x=>x.id===id)||state.records.find(x=>x.id===id);if(!entry){const d=await ai({text,organizations:state.organizations,key:config.key,model:config.model});entry=draftEntry(d,text,job.id);kind=d.kind;if(!entry)answer='尚未儲存，請補充後重新傳送完整內容：\n'+(d.warnings?.join('\n')||'請補充日期或對象。')+'\n\n你傳的內容：'+text.slice(0,1000);else{for(let attempt=0;attempt<5;attempt++){const latest=await store.read(),list=kind==='task'?'tasks':'records';if(latest[list].some(x=>x.id===id))break;const next=validateState({organizations:latest.organizations,records:latest.records,tasks:latest.tasks,[list]:[...latest[list],entry]});try{await store.save(latest.revision,next,'LINE:'+e.source.userId);break;}catch(err){if(err.status!==409||attempt===4)throw err;}}}}if(entry)answer='已記錄'+(kind==='task'?'待辦':'事項')+'：'+entry.title+'\n日期：'+(entry.dueDate||entry.date||'未指定')+(entry.endDate?' ～ '+entry.endDate:'')+'\n查看或修改：'+config.origin;}catch(err){answer=err.status?err.message+'\n請稍後重試；若先前已存入，請先查看清單。':'處理失敗，請先查看網頁清單是否已存入，再重試。';console.error('LINE processing failed:',err.status||err.code||err.name);}}}
 await store.pool.query('UPDATE cb_line_jobs SET reply_text=$2 WHERE id=$1',[job.id,answer]);}
 try{await reply(e,answer);await store.pool.query("UPDATE cb_line_jobs SET status='done',lease_until=NULL,event=event-'replyToken' WHERE id=$1",[job.id]);}catch(err){console.error('LINE reply failed:',err.message);await store.pool.query("UPDATE cb_line_jobs SET status='reply_failed',lease_until=NULL,event=event-'replyToken' WHERE id=$1",[job.id]);}}
 async function tick(){if(working||!enabled())return;working=true;try{const job=(await store.pool.query(`UPDATE cb_line_jobs SET status='processing',lease_until=now()+interval '2 minutes' WHERE id=(SELECT id FROM cb_line_jobs WHERE status='pending' OR (status='processing' AND lease_until<now()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`)).rows[0];if(job)await process(job);}catch(err){console.error('LINE worker failed:',err.code||err.name);}finally{working=false;}}
 function start(){timer=setInterval(()=>void tick(),500);timer.unref();void tick();}
 return {init,webhook,start,stop(){clearInterval(timer);},tick};
}
