import {createHmac,timingSafeEqual,createHash,randomUUID} from 'node:crypto';
import {AppError,validateState} from './domain.mjs';
import {AssistantStore} from './assistant-store.mjs';
import {understand,describeMedia,answerQuestion,expirySummary,expiryText,taipeiDay,taipeiHour} from './assistant.mjs';
const digest=s=>createHash('sha256').update(s).digest('hex');
export function validSignature(raw,signature,secret){if(!secret||typeof signature!=='string')return false;const a=Buffer.from(createHmac('sha256',secret).update(raw).digest('base64')),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}
export function draftEntry(d,text,eventId){if(d.warnings?.length||!d.title||!['record','task'].includes(d.kind)||(d.kind==='record'&&(!d.orgId||!d.date)))return null;const common={id:'line-'+digest(eventId).slice(0,48),title:d.title,note:d.note||'',sourceText:text};return d.kind==='task'?{...common,org:d.orgId||null,dueDate:d.date||null,done:false}:{...common,org:d.orgId,date:d.date,endDate:d.endDate||null,relatedOrg:null,type:d.type,amount:d.amount??null};}
export async function readLimited(response,max){const declared=Number(response.headers.get('content-length')||0);if(declared>max)throw new AppError(413,'附件太大，請縮短語音或縮小照片');let size=0,parts=[];for await(const b of response.body){size+=b.length;if(size>max)throw new AppError(413,'附件太大，請縮短語音或縮小照片');parts.push(Buffer.from(b));}return Buffer.concat(parts);}
export function createLineService({store,config,ai=understand,mediaAI=describeMedia,answerAI=answerQuestion,fetchImpl=fetch,now=()=>new Date(),assistantStore=new AssistantStore(store)}){
 const db=assistantStore,allowed=new Set((config.lineAllowedUsers||'').split(',').map(x=>x.trim()).filter(Boolean));let working=false,notifying=false,timer,reminderTimer;
 const reminderTime='每天台灣時間'+Number(config.reminderHour??8)+'點';
 const enabled=()=>Boolean(config.lineSecret&&config.lineToken);
 const permitted=id=>config.lineAccess!=='allowlist'||allowed.has(id);
 async function webhook(req){if(!config.lineSecret)throw new AppError(503,'尚未設定 LINE Channel Secret');let size=0,parts=[];for await(const p of req){size+=p.length;if(size>1024*1024)throw new AppError(413,'LINE 訊息過大');parts.push(p);}const raw=Buffer.concat(parts);if(!validSignature(raw,req.headers['x-line-signature'],config.lineSecret))throw new AppError(401,'LINE 簽章不正確');let p;try{p=JSON.parse(raw.toString('utf8'));}catch{throw new AppError(400,'LINE 訊息格式不正確');}if(!Array.isArray(p.events)||p.events.length>100)throw new AppError(400,'LINE 事件格式不正確');if(p.events.length&&!enabled())throw new AppError(503,'請先設定 LINE Token');const events=[];for(const e of p.events){const uid=e.source?.userId;if(e.source?.type!=='user'||typeof uid!=='string'||!permitted(uid))continue;if(!['message','follow','unfollow'].includes(e.type))continue;if(e.type==='unfollow'){await db.register(uid,'',false,e.timestamp||now().getTime());continue;}await db.register(uid,'',true,e.timestamp||now().getTime());if(typeof e.webhookEventId!=='string'||e.webhookEventId.length>100||typeof e.replyToken!=='string')continue;events.push(e);}await db.enqueue(events);return {ok:true};}
 async function callLine(path,data,retryKey){const r=await fetchImpl('https://api.line.me/v2/bot/message/'+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.lineToken,...(retryKey?{'X-Line-Retry-Key':retryKey}:{})},body:JSON.stringify(data),signal:AbortSignal.timeout(10000)});return r;}
 async function pushJob(id,uid,text){await db.notify('reply:'+id,uid,{messages:[{type:'text',text:text.slice(0,4900)}]},randomUUID());}
 async function deliver(job,text){let r;try{r=await callLine('reply',{replyToken:job.event.replyToken,messages:[{type:'text',text:text.slice(0,4900)}]});}catch{await db.finish(job.id,'reply_failed');return;}if(r.ok){await db.finish(job.id);return;}if(r.status===400&&config.linePushFallback!==false){await pushJob(job.id,job.event.source.userId,text);await db.finish(job.id,'push_queued');}else{console.error('LINE reply status:',r.status);await db.finish(job.id,'reply_failed');}}
 async function profile(uid){const member=await db.member(uid);if(member?.display_name)return member.display_name;try{const r=await fetchImpl('https://api.line.me/v2/bot/profile/'+encodeURIComponent(uid),{headers:{Authorization:'Bearer '+config.lineToken},signal:AbortSignal.timeout(10000)});if(r.ok){const p=await r.json(),name=typeof p.displayName==='string'?p.displayName.slice(0,100):'';if(name){await db.pool.query('UPDATE cb_line_members SET display_name=$2 WHERE user_id=$1',[uid,name]);return name;}}}catch{}return 'LINE管理者';}
 async function fetchMedia(e){const id='media-'+digest(e.message.id),existing=await db.media(id,true);if(existing)return existing;if(!/^[0-9A-Za-z_-]+$/.test(e.message.id||''))throw new AppError(400,'附件編號不正確');const r=await fetchImpl('https://api-data.line.me/v2/bot/message/'+encodeURIComponent(e.message.id)+'/content',{headers:{Authorization:'Bearer '+config.lineToken},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new AppError(502,'無法下載 LINE 附件，請重新傳送');const mime=(r.headers.get('content-type')||'').split(';')[0].toLowerCase(),image=['image/jpeg','image/png','image/webp'],audio=['audio/mp4','audio/mpeg','audio/aac','audio/wav','audio/x-wav','audio/ogg','audio/flac','audio/webm'];if(!(e.message.type==='image'?image:audio).includes(mime))throw new AppError(415,'此附件格式尚不支援');if(e.message.type==='audio'&&Number(e.message.duration)>300000)throw new AppError(413,'語音請控制在5分鐘內');const body=await readLimited(r,e.message.type==='image'?8*1024*1024:10*1024*1024),ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','audio/mp4':'m4a','audio/mpeg':'mp3','audio/aac':'aac','audio/wav':'wav','audio/x-wav':'wav','audio/ogg':'ogg','audio/flac':'flac','audio/webm':'webm'}[mime];const m={id,mime,name:(e.message.type==='image'?'照片':'語音')+'-'+taipeiDay(now())+'.'+ext,body,owner_id:e.source.userId};await db.putMedia(m);return m;}
 async function saveEntry(entry,kind,actor,targetId){return db.mutate(state=>{const list=kind==='task'?'tasks':'records';if(state.records.some(x=>x.id===entry.id)||state.tasks.some(x=>x.id===entry.id))return null;const target=targetId?state.records.find(x=>x.id===targetId):null;const item=target?{...target,...entry,id:target.id,attachments:target.attachments,createdBy:target.createdBy,createdByName:target.createdByName,createdAt:target.createdAt,sourceKind:'photo-caption',captionEventId:entry.id}:entry;if(state.records.some(x=>x.captionEventId===entry.id))return null;return validateState({organizations:state.organizations,records:state.records,tasks:state.tasks,[list]:target?state.records.map(x=>x.id===target.id?item:x):[...state[list],item]});},actor);}
 async function handle(job){const e=job.event,uid=e.source.userId;if(e.type==='follow')return '歡迎使用公司秘書。可傳文字、照片或語音紀錄，也能問「日航有沒有客訴？」。'+reminderTime+'發送到期清單，可傳「關閉提醒」。網頁：'+config.origin;const name=await profile(uid),kind=e.message?.type;if(!['text','image','audio'].includes(kind))return '請傳文字、照片或5分鐘內語音。';let text=kind==='text'?e.message.text:'',media=null,uncertain=false;if(typeof text!=='string'||text.length>8000)throw new AppError(400,'請使用8000字以內的文字');const state=await store.read(),id='line-'+digest(job.id).slice(0,48),existing=state.records.find(x=>x.id===id||x.captionEventId===id)||state.tasks.find(x=>x.id===id);if(existing)return '這筆資料已記錄：'+existing.title+'\n'+config.origin+'/?record='+encodeURIComponent(existing.id);
 if(kind==='text'){const command=text.trim();if(['說明','help','開始'].includes(command.toLowerCase()))return '直接傳文字、照片或語音。\n紀錄：2026/10/18 金澤出差。\n查詢：日航有沒有客訴？\n到期：查看到期\n通知：開啟提醒／關閉提醒\n照片補充：這張照片是2026/10/9日航枕套髒污（傳照片後15分鐘內）。\n'+config.origin;if(command==='關閉提醒'||command==='開啟提醒'){await db.subscription(uid,command==='開啟提醒');return command==='開啟提醒'?'已開啟'+reminderTime+'的到期提醒。':'已關閉你的到期提醒，其他人不受影響。';}if(command==='查看到期')return expiryText(expirySummary(state,taipeiDay(now())))+'\n'+config.origin;}
 if(kind!=='text'){media=await fetchMedia(e);try{const r=await mediaAI({body:media.body,mime:media.mime,type:kind==='image'?'image':'audio',key:config.key,model:config.model,fetchImpl});text=r.text;uncertain=r.uncertain;}catch(err){text='附件已保存；AI 尚未成功辨識，請在網頁補充。';uncertain=true;console.error('LINE media analysis failed:',err.status||err.name);}}
 const meta={createdBy:uid,createdByName:name,createdAt:now().toISOString(),sourceKind:kind==='image'?'photo':kind==='audio'?'voice':'line'};
 const attachment=media?{id:media.id,mime:media.mime,name:media.name}:null;
 if(kind==='image'||(kind==='audio'&&uncertain)){const entry={id,title:kind==='image'?'照片收件｜'+text.slice(0,65):'語音收件｜待確認',org:'baiqi',date:taipeiDay(now()),endDate:null,relatedOrg:null,type:'一般紀錄',amount:null,note:('收件日期為上傳日，不代表事件發生日。\n'+text).slice(0,8000),sourceText:text,attachments:[attachment],...meta};await saveEntry(entry,'record','LINE:'+uid);return '已保存'+(kind==='image'?'照片':'語音')+'與'+(uncertain?'待確認內容':'辨識內容')+'。\n照片可再傳「這張照片是2026/10/9日航客訴…」補充歸檔。\n'+config.origin+'/?record='+encodeURIComponent(id);}
 let target=null;if(kind==='text'&&/^(這張照片|剛剛的?照片|照片補充|照片：)/.test(text.trim())){target=state.records.filter(r=>r.createdBy===uid&&r.sourceKind==='photo'&&now().getTime()-Date.parse(r.createdAt)<15*60*1000).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];if(!target)return '沒有找到你15分鐘內上傳的照片，請先傳照片再補充。';text=(text+'\n照片辨識內容（不是事件日期依據）：'+target.sourceText).slice(0,8000);}
 let d;try{d=await ai({text,organizations:state.organizations,key:config.key,model:config.model,now:now(),fetchImpl});}catch(err){if(!media)throw err;d={warnings:['AI 分類暫時失敗，請在網頁補充。']};}if(d.kind==='query'){const r=await answerAI({text,state,plan:d,key:config.key,model:config.model,origin:config.origin,fetchImpl});return r.answer+(r.sources.length?'\n\n來源：\n'+r.sources.map((x,i)=>(i+1)+'. '+x.date+' '+x.title+'\n'+x.url).join('\n'):'');}
 const entry=draftEntry(d,text,job.id);if(!entry){if(media){const pending={id,title:'語音收件｜待補充',org:'baiqi',date:taipeiDay(now()),endDate:null,relatedOrg:null,type:'一般紀錄',amount:null,note:('待確認：'+(d.warnings||[]).join('；')+'\n逐字稿：'+text).slice(0,8000),sourceText:text,attachments:[attachment],...meta};await saveEntry(pending,'record','LINE:'+uid);return '已保存語音與逐字稿，日期或對象需要確認：\n'+(d.warnings||[]).join('\n')+'\n'+config.origin+'/?record='+encodeURIComponent(id);}return '尚未儲存，請補充後重新傳完整內容：\n'+(d.warnings?.join('\n')||'請補日期或對象。');}
 if(target&&d.kind!=='record')return '照片補充請描述事件，待辦請另傳一則訊息。';Object.assign(entry,meta,media?{attachments:[attachment]}:{});await saveEntry(entry,d.kind,'LINE:'+uid,target?.id);const savedId=target?.id||id;return '已記錄'+(d.kind==='task'?'待辦':'事項')+'：'+entry.title+'\n日期：'+(entry.dueDate||entry.date||'未指定')+(entry.endDate?' ～ '+entry.endDate:'')+(kind==='audio'?'\n語音逐字稿：'+text.slice(0,800):'')+'\n查看或修改：'+config.origin+'/?record='+encodeURIComponent(savedId);}
 async function tick(){if(working||!enabled())return;working=true;try{const job=await db.claim();if(!job)return;const member=await db.member(job.event.source.userId);if(member&&!member.active){await db.finish(job.id,'blocked');return;}let answer=job.reply_text;if(!answer){try{answer=await handle(job);}catch(err){answer=(err.status?err.message:'處理失敗，請先查看網頁清單後重試。');console.error('LINE processing failed:',err.status||err.code||err.name);}await db.answer(job.id,answer);}await deliver(job,answer);}catch(err){console.error('LINE worker failed:',err.code||err.name);}finally{working=false;}}
 async function reminderTick(){if(notifying||!enabled())return;notifying=true;try{if(config.lineReminders!==false&&taipeiHour(now())>=Number(config.reminderHour??8)){const state=await store.read(),summary=expirySummary(state,taipeiDay(now()));if(summary.tasks.length||summary.contracts.length){const users=(await db.pool.query('SELECT user_id FROM cb_line_members WHERE active=true AND reminders=true')).rows;for(const u of users)if(permitted(u.user_id))await db.notify('daily:'+summary.day+':'+u.user_id,u.user_id,{messages:[{type:'text',text:expiryText(summary)+'\n'+config.origin}]},randomUUID());}}
 const notice=await db.claimNotice();if(notice){const member=await db.member(notice.user_id);if(!member?.active||!permitted(notice.user_id)||notice.id.startsWith('daily:')&&!member.reminders){await db.finishNotice(notice.id,'cancelled');return;}let response;try{response=await callLine('push',{to:notice.user_id,...notice.payload},notice.retry_key);}catch{await db.finishNotice(notice.id,'pending',true);return;}if(response.ok||response.status===409)await db.finishNotice(notice.id,'sent');else if(response.status===429||response.status>=500)await db.finishNotice(notice.id,'pending',true);else{console.error('LINE push status:',response.status);await db.finishNotice(notice.id,'failed');}}}catch(err){console.error('LINE reminder failed:',err.code||err.name);}finally{notifying=false;}}
 return {init:()=>db.init(),webhook,tick,reminderTick,db,start(){timer=setInterval(()=>void tick(),500);timer.unref();reminderTimer=setInterval(()=>void reminderTick(),30000);reminderTimer.unref();void tick();void reminderTick();},stop(){clearInterval(timer);clearInterval(reminderTimer);}};
}
