import http from 'node:http';
import {fileURLToPath} from 'node:url';
import {Store} from './store.mjs';
import {createHandler} from './app.mjs';
import {createLineService} from './line.mjs';
const env=process.env;
if(!env.ADMIN_PASSWORD||env.ADMIN_PASSWORD.startsWith('CHANGE_ME')||env.ADMIN_PASSWORD.length<16)throw new Error('ADMIN_PASSWORD must be changed to at least 16 characters');
if(!env.PGPASSWORD||env.PGPASSWORD.startsWith('CHANGE_ME')||env.PGPASSWORD.length<24)throw new Error('DB_PASSWORD must be changed to at least 24 characters');
const origin=new URL(env.PUBLIC_ORIGIN).origin,secure=env.COOKIE_SECURE!=='false';
if(secure&&!origin.startsWith('https://'))throw new Error('Secure mode requires an HTTPS PUBLIC_ORIGIN');
const store=new Store();await store.init(env.ADMIN_USER||'admin1',env.ADMIN_PASSWORD);
const config={origin,secure,key:env.GEMINI_API_KEY||'',model:env.GEMINI_MODEL||'gemini-3.1-flash-lite',lineSecret:env.LINE_CHANNEL_SECRET||'',lineToken:env.LINE_CHANNEL_ACCESS_TOKEN||'',lineAllowedUsers:env.LINE_ALLOWED_USER_IDS||''};
const line=createLineService({store,config});await line.init();line.start();
const server=http.createServer(createHandler({store,config,line,htmlPath:fileURLToPath(new URL('./public/index.html',import.meta.url))}));
server.requestTimeout=60000;server.headersTimeout=15000;server.listen(Number(env.PORT||8788),'0.0.0.0',()=>console.log('companybrain-api ready on port '+(env.PORT||8788)));
