import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createHandler} from '../backend/app.mjs';import {initialState,AppError,validateState,normalizeDraft,dateOK} from '../backend/domain.mjs';import {hashPassword,verifyPassword} from '../backend/security.mjs';import {extractDraft} from '../backend/gemini.mjs';
class MemoryStore {constructor(){this.state={revision:0,...structuredClone(initialState)};this.sessions=new Map()}async health(){}async user(n){return n==='admin1'?{password_hash:this.hash}:null}async addSession(h,u,csrf){this.sessions.set(h,{username:u,csrf})}async session(h){return this.sessions.get(h)}async deleteSession(h){this.sessions.delete(h)}async read(){return structuredClone(this.state)}async save(rev,state){if(rev!==this.state.revision)throw new AppError(409,'conflict');this.state={revision:rev+1,...structuredClone(state)};return this.read()}}
test('attachments require login and support audio ranges; questions are CSRF protected and read-only',async()=>{
 const store=new MemoryStore();store.hash=hashPassword('abcdefghijklmnop');const origin='http://companybrain.test',mediaId='media-'+ 'a'.repeat(64);let queries=0;
 const server=http.createServer(createHandler({store,config:{origin,secure:false,key:'key',model:'model'},htmlPath:new URL('../index.html',import.meta.url),line:{db:{media:async id=>id===mediaId?{mime:'audio/mp4',name:'語音.m4a',body:Buffer.from('0123456789')}:null}},queryAI:async()=>({kind:'query',keywords:['人事']}),answerAI:async()=>{queries++;return {answer:'已有資料',sources:[]}}}));await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 try{assert.equal((await fetch(url+'/api/files/'+mediaId)).status,401);const login=await fetch(url+'/api/login',{method:'POST',headers:{Origin:origin,'content-type':'application/json'},body:JSON.stringify({username:'admin1',password:'abcdefghijklmnop'})});const cookie=login.headers.get('set-cookie').split(';')[0],csrf=(await login.json()).csrf;
 const full=await fetch(url+'/api/files/'+mediaId,{headers:{Cookie:cookie}});assert.equal(full.status,200);assert.equal(await full.text(),'0123456789');const part=await fetch(url+'/api/files/'+mediaId,{headers:{Cookie:cookie,Range:'bytes=2-5'}});assert.equal(part.status,206);assert.equal(part.headers.get('content-range'),'bytes 2-5/10');assert.equal(await part.text(),'2345');assert.equal((await fetch(url+'/api/files/'+mediaId,{headers:{Cookie:cookie,Range:'bytes=20-'}})).status,416);
 const headers={Origin:origin,Cookie:cookie,'content-type':'application/json'};assert.equal((await fetch(url+'/api/ai/question',{method:'POST',headers,body:'{"text":"查人事"}'})).status,403);headers['x-csrf-token']=csrf;assert.equal((await fetch(url+'/api/ai/question',{method:'POST',headers,body:'{"text":"查人事"}'})).status,200);assert.equal(queries,1);assert.equal(store.state.revision,0);
 }finally{await new Promise(r=>server.close(r))}
});
test('validates records, dates and passwords',()=>{assert(dateOK('2028-02-29'));assert(!dateOK('2026-02-29'));assert(verifyPassword('abcdefghijklmnop',hashPassword('abcdefghijklmnop')));assert(!verifyPassword('wrong',hashPassword('abcdefghijklmnop')));assert.deepEqual(validateState(initialState),initialState);const state=structuredClone(initialState);state.records=[{id:'1',org:'missing',title:'test',note:'',date:'2026-10-07',type:'客訴',amount:null}];assert.throws(()=>validateState(state));});
test('AI missing year is retained as warning; no database write',async()=>{const organizations=initialState.organizations;let called;const draft=await extractDraft({text:'上海出差',organizations,key:'test-key',model:'gemini-3.1-flash-lite',fetchImpl:async(url,options)=>{called={url,options};return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify({kind:'record',orgId:'baiqi',type:'出差／展覽',title:'上海出差',note:'商務艙',date:null,endDate:null,amount:null,warnings:[]})}]}}]})}}});assert.equal(draft.date,null);assert(draft.warnings.some(x=>x.includes('年份')));assert(!called.url.includes('test-key'));assert.equal(called.options.headers['x-goog-api-key'],'test-key');assert(JSON.parse(called.options.body).generationConfig.responseJsonSchema);await assert.rejects(extractDraft({text:'x',organizations,key:'test',model:'gemini-3.1-flash-lite',fetchImpl:async()=>({ok:false,status:429})}),/額度/);});
test('HTTP authentication, CSRF, persistence, conflict and logout',async()=>{const store=new MemoryStore();store.hash=hashPassword('abcdefghijklmnop');let aiCalls=0;const origin='http://companybrain.test';const server=http.createServer(createHandler({store,config:{origin,secure:false,key:'key',model:'model'},htmlPath:new URL('../index.html',import.meta.url),ai:async()=>{aiCalls++;return {kind:'task',title:'草稿'}}}));await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;let cookie='',csrf='';async function api(path,method='GET',body,extra={}){return fetch(url+path,{method,headers:{Origin:origin,'content-type':'application/json',Cookie:cookie,'x-csrf-token':csrf,...extra},...(body?{body:JSON.stringify(body)}:{})})}try{assert.equal((await api('/api/state')).status,401);const html=await(await api('/')).text();assert(html.includes('companybrain-runtime'));assert.equal((await api('/api/login','POST',{username:'admin1',password:'bad'})).status,401);const login=await api('/api/login','POST',{username:'admin1',password:'abcdefghijklmnop'});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];csrf=(await login.json()).csrf;assert(login.headers.get('set-cookie').includes('HttpOnly'));assert.equal((await api('/api/state','PUT',store.state,{'x-csrf-token':'bad'})).status,403);const next=await(await api('/api/state')).json();next.tasks.push({id:'t1',title:'測試',org:'baiqi',dueDate:'2026-10-07',note:'',done:false});const saved=await api('/api/state','PUT',next);assert.equal(saved.status,200);assert.equal((await saved.json()).revision,1);assert.equal((await api('/api/state','PUT',next)).status,409);assert.equal((await api('/api/state','PUT',{...next,revision:1},{Origin:'http://evil.test'})).status,403);assert.equal((await api('/api/ai/draft','POST',{text:'提醒'})).status,200);assert.equal(aiCalls,1);assert.equal(store.state.tasks.length,1);assert.equal((await api('/api/logout','POST',{})).status,200);assert.equal((await api('/api/state')).status,401);}finally{await new Promise(r=>server.close(r))}});
