import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const domain=(await readFile(new URL('backend/domain.mjs',root),'utf8')).replaceAll('export ','');
const gemini=(await readFile(new URL('backend/gemini.mjs',root),'utf8')).replace(/^import .*\n/,'').replaceAll('export ','');
const worker=(await readFile(new URL('cloudflare/worker.mjs',root),'utf8')).replace(/^import .*\n/gm,'').replace(/export async function/g,'async function').replace(/export function/g,'function');
await writeFile(new URL('cloudflare/worker-paste.js',root),'// Generated by node cloudflare/build.mjs; paste this entire file into Cloudflare Worker.\n'+domain+'\n'+gemini+'\n'+worker);
