import {extractDraft} from '../backend/gemini.mjs';
import {dateOK,validateState} from '../backend/domain.mjs';
const help='百麒公司秘書\n直接傳文字 → AI 草稿 → 確認後儲存。\n\n指令：\n新增對象 飯店 日航飯店\n對象 日航飯店（修改最近草稿）\n日期 2026-09-20（修改最近草稿）\n最近草稿\n說明\n\n目前只處理文字，沒有照片、語音、搜尋或定時通知；資料先存 Cloudflare，尚未同步 NAS。';
const encoder=new TextEncoder();
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function sameSecret(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const hashes=await Promise.all([a,b].map(x=>crypto.subtle.digest('SHA-256',encoder.encode(x))));const x=new Uint8Array(hashes[0]),y=new Uint8Array(hashes[1]);let v=0;for(let i=0;i<x.length;i++)v|=x[i]^y[i];return v===0;}
export async function verifySignature(raw,signature,secret){if(!secret||!signature)return false;let bytes;try{bytes=Uint8Array.from(atob(signature),c=>c.charCodeAt(0))}catch{return false}const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);return crypto.subtle.verify('HMAC',key,bytes,encoder.encode(raw));}
async function reply(env,replyToken,text,actions=[]){if(!replyToken)return;const message={type:'text',text:text.slice(0,4900)};if(actions.length)message.quickReply={items:actions.map(a=>({type:'action',action:{type:'message',label:a.label,text:a.text}}))};const response=await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{authorization:'Bearer '+env.LINE_CHANNEL_ACCESS_TOKEN,'content-type':'application/json'},body:JSON.stringify({replyToken,messages:[message]}),signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('LINE_REPLY_'+response.status);}
async function allowed(env,user){const explicit=(env.LINE_ALLOWED_USER_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);if(explicit.length)return explicit.includes(user);const owner=await env.DB.prepare('SELECT user_id FROM line_owner WHERE id=1').first();return owner?.user_id===user;}
async function limited(env,id,max){const now=Date.now();await env.DB.prepare('INSERT INTO line_auth_attempts(id,n,created_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET n=n+1').bind(id,now).run();return (await env.DB.prepare('SELECT n FROM line_auth_attempts WHERE id=?').bind(id).first()).n>max;}
async function latest(env,user){return env.DB.prepare("SELECT * FROM line_drafts WHERE user_id=? AND status='pending' AND expires_at>? ORDER BY created_at DESC LIMIT 1").bind(user,Date.now()).first();}
function draftText(d,orgs){const p=JSON.parse(d.payload),org=orgs.find(o=>o.id===p.orgId);return `草稿 ${d.id}\n${p.kind==='task'?'待辦事項':'往來紀錄'}｜${p.title}\n對象：${org?.name||'尚未指定'}\n日期：${p.date||'尚未指定'}${p.endDate?' ～ '+p.endDate:''}\n分類：${p.type}\n金額：${p.amount===null?'未提供':p.amount}\n\n${p.note.slice(0,2200)}\n${p.warnings.length?'\n請確認：'+p.warnings.join('；'):''}\n\n尚未儲存。可傳「日期 YYYY-MM-DD」或「對象 名稱」修正；確認／取消可按下方按鈕。待辦日期不會自動通知。`;}
async function showDraft(env,token,d,orgs){return reply(env,token,draftText(d,orgs),[{label:'確認儲存',text:'確認 '+d.id},{label:'取消草稿',text:'取消 '+d.id}]);}
export function savedPayload(d,id){const p=JSON.parse(d.payload),base={id:'line-'+id,title:p.title,note:p.note,org:p.orgId||'',sourceText:d.source_text};return p.kind==='task'?{...base,dueDate:p.date||'',done:false}:{...base,date:p.date,endDate:p.endDate||'',type:p.type,amount:p.amount};}
async function organizations(env){const {results}=await env.DB.prepare('SELECT payload FROM line_orgs ORDER BY name').all();return results.map(x=>JSON.parse(x.payload));}
async function confirmDraft(env,user,id){const d=await env.DB.prepare('SELECT * FROM line_drafts WHERE id=? AND user_id=?').bind(id,user).first();if(!d)return '找不到你的這筆草稿。';if(d.status==='saved')return '這筆已儲存，不會重複新增。';if(d.status!=='pending'||d.expires_at<Date.now())return '草稿已取消或超過24小時，請重新傳送文字。';const p=JSON.parse(d.payload),orgs=await organizations(env);if(p.kind==='record'&&(!p.orgId||!dateOK(p.date)))return '尚未儲存：請先指定對象及完整日期。可傳「對象 百麒」及「日期 2026-09-20」，再按確認。';const payload=savedPayload(d,id);validateState({organizations:orgs,records:p.kind==='record'?[payload]:[],tasks:p.kind==='task'?[payload]:[]});const now=Date.now();await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO line_saved(id,user_id,kind,payload,created_at) SELECT id,user_id,?,?,? FROM line_drafts WHERE id=? AND user_id=? AND status='pending' AND expires_at>?").bind(p.kind,JSON.stringify(payload),now,id,user,now),env.DB.prepare("UPDATE line_drafts SET status='saved' WHERE id=? AND user_id=? AND status='pending' AND EXISTS(SELECT 1 FROM line_saved WHERE id=?)").bind(id,user,id)]);const saved=await env.DB.prepare('SELECT id FROM line_saved WHERE id=? AND user_id=?').bind(id,user).first();return saved?'已儲存在 Cloudflare：'+payload.title+'\n尚未同步 NAS；之後可匯出搬移。':'草稿已取消或到期，未儲存。';}
async function processEvent(event,env){if(event.source?.type!=='user'||!event.source.userId||!event.replyToken)return;const user=event.source.userId,text=event.type==='message'&&event.message?.type==='text'?event.message.text.trim():'';
 if(!await allowed(env,user)){if(text.startsWith('綁定 ')){if(!env.BIND_CODE||env.BIND_CODE.length<16)return reply(env,event.replyToken,'管理員尚未設定16字以上 BIND_CODE。');if(await limited(env,'bind:'+user+':'+Math.floor(Date.now()/3600000),5))return reply(env,event.replyToken,'綁定嘗試太多，請一小時後再試。');if(await sameSecret(text.slice(3).trim(),env.BIND_CODE)){await env.DB.prepare('INSERT OR IGNORE INTO line_owner(id,user_id) VALUES (1,?)').bind(user).run();if(await allowed(env,user))return reply(env,event.replyToken,'綁定完成。這個秘書目前只接受你的私人訊息。\n'+help);}}return reply(env,event.replyToken,'此帳號尚未授權你使用。第一次請傳「綁定 你的設定碼」。');}
 const eventId=event.webhookEventId||event.message?.id;if(!eventId)return;const inserted=await env.DB.prepare('INSERT OR IGNORE INTO line_events(id,user_id,created_at) VALUES (?,?,?)').bind(eventId,user,Date.now()).run();if(!inserted.meta.changes)return;
 try{if(event.type==='follow'||text==='說明')return await reply(env,event.replyToken,help);if(!text)return await reply(env,event.replyToken,'這一版先支援文字。照片、語音請先改成文字描述。');if(text.length>8000)return await reply(env,event.replyToken,'文字超過8000字，請分段傳送。');if(text==='我的ID')return await reply(env,event.replyToken,'你的 LINE user ID：'+user);
 const orgs=await organizations(env);
 if(text==='最近草稿'){const d=await latest(env,user);return d?await showDraft(env,event.replyToken,d,orgs):await reply(env,event.replyToken,'沒有待確認的草稿。');}
 const confirm=text.match(/^確認 ([a-f0-9]{16})$/);if(confirm)return await reply(env,event.replyToken,await confirmDraft(env,user,confirm[1]));
 const cancel=text.match(/^取消 ([a-f0-9]{16})$/);if(cancel){await env.DB.prepare("UPDATE line_drafts SET status='cancelled' WHERE id=? AND user_id=? AND status='pending'").bind(cancel[1],user).run();return await reply(env,event.replyToken,'已處理取消要求；已儲存的紀錄不會被刪除。');}
 const add=text.match(/^新增對象 (飯店|設備商|工程\s*\/\s*建築|內部) (.{1,100})$/);if(add){const name=add[2].trim(),o={id:crypto.randomUUID(),name,kind:add[1].replace(/\s/g,''),mark:name.slice(0,1),en:'',contact:'尚未提供',role:'尚未提供',manager:'尚未提供',contract:'尚未提供',memo:'LINE 建立',prices:[]};await env.DB.prepare('INSERT OR IGNORE INTO line_orgs(id,name,payload) VALUES (?,?,?)').bind(o.id,name,JSON.stringify(o)).run();return await reply(env,event.replyToken,'對象已建檔：'+name+'。可重新傳送紀錄或用「對象 '+name+'」修正最近草稿。');}
 if(text.startsWith('日期 ')||text.startsWith('對象 ')){const d=await latest(env,user);if(!d)return await reply(env,event.replyToken,'沒有待確認的草稿，請先傳紀錄文字。');const p=JSON.parse(d.payload);if(text.startsWith('日期 ')){const date=text.slice(3).trim();if(!dateOK(date))return await reply(env,event.replyToken,'請使用完整日期，例如「日期 2026-09-20」。');if(p.endDate&&p.endDate<date)return await reply(env,event.replyToken,'開始日期晚於結束日期，請重新傳送完整日期區間產生新草稿。');p.date=date;p.warnings=p.warnings.filter(x=>!/(日期|年份)/.test(x));}else{const org=orgs.find(o=>o.name===text.slice(3).trim());if(!org)return await reply(env,event.replyToken,'對象尚未建檔，先傳「新增對象 飯店 對象名稱」。');p.orgId=org.id;p.warnings=p.warnings.filter(x=>!/(對象)/.test(x));}d.payload=JSON.stringify(p);await env.DB.prepare("UPDATE line_drafts SET payload=? WHERE id=? AND user_id=? AND status='pending'").bind(d.payload,d.id,user).run();return await showDraft(env,event.replyToken,d,orgs);}
 if(await limited(env,'ai:'+user+':'+Math.floor(Date.now()/60000),5)||await limited(env,'ai-day:'+user+':'+Math.floor(Date.now()/86400000),100))return await reply(env,event.replyToken,'AI 使用次數暫時達到上限，請稍後再試。');
 const p=await extractDraft({text,organizations:orgs,key:env.GEMINI_API_KEY,model:env.GEMINI_MODEL||'gemini-3.1-flash-lite',fetchImpl:(url,options)=>fetch(url,{...options,signal:AbortSignal.timeout(18000)})});const now=Date.now(),d={id:crypto.randomUUID().replaceAll('-','').slice(0,16),payload:JSON.stringify(p),source_text:text};await env.DB.prepare('INSERT INTO line_drafts(id,user_id,payload,source_text,expires_at,created_at) VALUES (?,?,?,?,?,?)').bind(d.id,user,d.payload,text,now+86400000,now).run();await showDraft(env,event.replyToken,d,orgs);
 }catch(e){console.error('LINE event processing failed',e.status||'internal');try{await reply(env,event.replyToken,e.status?e.message.replaceAll('NAS','Cloudflare')+'\n沒有新增正式紀錄；若草稿回覆遺失，請傳「最近草稿」。':'處理未完成，請傳「最近草稿」確認狀態，或稍後再試。')}catch{console.error('LINE error reply failed')}}}
const exportPage='<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>百麒資料匯出</title><body style="font:16px system-ui;max-width:600px;margin:60px auto;padding:24px;color:#243746"><h1>LINE 暫存資料匯出</h1><p>輸入 Cloudflare 設定的 EXPORT_KEY，下載已確認的公司紀錄。草稿不會匯出。</p><form method="post" action="/export"><input type="password" name="key" required autocomplete="off" placeholder="匯出金鑰"><button>下載 JSON</button></form></body></html>';
export default {async fetch(request,env,ctx){const path=new URL(request.url).pathname;
 if(request.method==='GET'&&path==='/')return json({service:'companybrain-line',storage:'cloudflare-d1',nasConnected:false});
 if(request.method==='GET'&&path==='/export')return new Response(exportPage,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','referrer-policy':'no-referrer','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'"}});
 if(!env.DB)return json({error:'尚未綁定 D1 DB'},503);
 if(request.method==='POST'&&path==='/export'){if(!env.EXPORT_KEY||env.EXPORT_KEY.length<32)return json({error:'尚未設定32字以上 EXPORT_KEY'},503);const ip=request.headers.get('cf-connecting-ip')||'unknown';if(await limited(env,'export:'+ip+':'+Math.floor(Date.now()/60000),8))return json({error:'請稍後重試'},429);if(Number(request.headers.get('content-length')||0)>4096)return json({error:'請求太大'},413);const form=await request.formData();if(!await sameSecret(form.get('key'),env.EXPORT_KEY))return json({error:'匯出金鑰不正確'},403);const orgs=await organizations(env),{results}=await env.DB.prepare('SELECT kind,payload FROM line_saved ORDER BY created_at').all();const data={version:1,organizations:orgs,records:results.filter(x=>x.kind==='record').map(x=>JSON.parse(x.payload)),tasks:results.filter(x=>x.kind==='task').map(x=>JSON.parse(x.payload))};return new Response(JSON.stringify(data,null,2),{headers:{'content-type':'application/json; charset=utf-8','content-disposition':'attachment; filename="companybrain-line.json"','cache-control':'no-store'}});}
 if(path!=='/webhook'||request.method!=='POST')return json({error:'找不到此頁面'},404);
 if(!env.LINE_CHANNEL_SECRET||!env.LINE_CHANNEL_ACCESS_TOKEN)return json({error:'LINE 設定未完成'},503);
 if(Number(request.headers.get('content-length')||0)>1000000)return json({error:'請求太大'},413);const raw=await request.text();if(raw.length>1000000)return json({error:'請求太大'},413);if(!await verifySignature(raw,request.headers.get('x-line-signature'),env.LINE_CHANNEL_SECRET))return json({error:'簽章不符'},401);let data;try{data=JSON.parse(raw)}catch{return json({error:'JSON 不正確'},400)}if(!Array.isArray(data.events)||data.events.length>20)return json({error:'事件格式不正確'},400);
 // Confirm D1 schema exists before acknowledging LINE verification or events.
 try{await env.DB.prepare('SELECT id FROM line_owner LIMIT 1').all()}catch{return json({error:'請先執行 schema.sql 建表'},503)}
 const job=Promise.all(data.events.map(event=>processEvent(event,env).catch(()=>console.error('LINE event failed'))));ctx.waitUntil(job);return json({ok:true});
 }};
